import type { ColorMoodId, Palette, StyleOption } from "@/types";

export interface ColorMoodData extends StyleOption<ColorMoodId> {
  swatches: string[];
}

export const colorMoods: ColorMoodData[] = [
  {
    id: "warm",
    label: "Warm",
    labelTh: "อบอุ่น",
    description: "Reds, oranges, yellows. Energetic, friendly, inviting.",
    descriptionTh: "แดง ส้ม เหลือง เป็นมิตร",
    swatches: ["#DC2626", "#F97316", "#FBBF24", "#FEF3C7", "#7C2D12"],
  },
  {
    id: "cool",
    label: "Cool",
    labelTh: "เย็น",
    description: "Blues, greens, purples. Calm, trustworthy.",
    descriptionTh: "น้ำเงิน เขียว ม่วง น่าเชื่อถือ",
    swatches: ["#2563EB", "#0EA5E9", "#10B981", "#8B5CF6", "#1E1B4B"],
  },
  {
    id: "neutral",
    label: "Neutral",
    labelTh: "กลาง",
    description: "Greys, beiges. Timeless, sophisticated.",
    descriptionTh: "เทา ครีม คลาสสิก หรูเรียบ",
    swatches: ["#FAFAF9", "#E7E5E4", "#A8A29E", "#57534E", "#1C1917"],
  },
  {
    id: "high-contrast",
    label: "High Contrast",
    labelTh: "ตัดกันสูง",
    description: "Black/white with one bold accent.",
    descriptionTh: "ดำ-ขาวกับสีเด่นสีเดียว",
    swatches: ["#000000", "#FFFFFF", "#FF0080", "#000000", "#FFFFFF"],
  },
  {
    id: "pastel",
    label: "Pastel",
    labelTh: "พาสเทล",
    description: "Soft, washed-out. Gentle, dreamy.",
    descriptionTh: "นุ่ม ฟุ้ง อ่อนโยน",
    swatches: ["#FBCFE8", "#BFDBFE", "#BBF7D0", "#FEF3C7", "#DDD6FE"],
  },
  {
    id: "earthy",
    label: "Earthy",
    labelTh: "ดิน-ธรรมชาติ",
    description: "Terracotta, olive, sage. Organic, grounded.",
    descriptionTh: "ดินเผา มะกอก เซจ ออร์แกนิก",
    swatches: ["#A0522D", "#8B6F47", "#65A30D", "#84764C", "#3E2723"],
  },
  {
    id: "vibrant",
    label: "Vibrant",
    labelTh: "สีจัด",
    description: "Saturated, neon, gradients. Bold, youthful.",
    descriptionTh: "อิ่มสี นีออน ไล่สี",
    swatches: ["#EC4899", "#06B6D4", "#FACC15", "#10B981", "#7C3AED"],
  },
];

export const presetPalettes: Palette[] = [
  {
    id: "nordic",
    name: "Nordic",
    primary: "#5E81AC",
    secondary: "#88C0D0",
    accent: "#EBCB8B",
    background: "#ECEFF4",
    foreground: "#2E3440",
    muted: "#D8DEE9",
    border: "#D8DEE9",
    mode: "light",
  },
  {
    id: "sunset",
    name: "Sunset",
    primary: "#F97316",
    secondary: "#FB923C",
    accent: "#DB2777",
    background: "#FFF7ED",
    foreground: "#431407",
    muted: "#FED7AA",
    border: "#FDBA74",
    mode: "light",
  },
  {
    id: "forest",
    name: "Forest",
    primary: "#15803D",
    secondary: "#65A30D",
    accent: "#CA8A04",
    background: "#F7FEE7",
    foreground: "#14532D",
    muted: "#D9F99D",
    border: "#BEF264",
    mode: "light",
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    primary: "#EC4899",
    secondary: "#06B6D4",
    accent: "#FACC15",
    background: "#0F172A",
    foreground: "#F1F5F9",
    muted: "#1E293B",
    border: "#334155",
    mode: "dark",
  },
  {
    id: "pastel-dream",
    name: "Pastel Dream",
    primary: "#C084FC",
    secondary: "#F0ABFC",
    accent: "#FBCFE8",
    background: "#FDF4FF",
    foreground: "#581C87",
    muted: "#F3E8FF",
    border: "#E9D5FF",
    mode: "light",
  },
  {
    id: "corporate-blue",
    name: "Corporate Blue",
    primary: "#1E40AF",
    secondary: "#3B82F6",
    accent: "#0EA5E9",
    background: "#FFFFFF",
    foreground: "#0F172A",
    muted: "#F1F5F9",
    border: "#E2E8F0",
    mode: "light",
  },
  {
    id: "monochrome",
    name: "Monochrome",
    primary: "#171717",
    secondary: "#525252",
    accent: "#A3A3A3",
    background: "#FAFAFA",
    foreground: "#0A0A0A",
    muted: "#F5F5F5",
    border: "#E5E5E5",
    mode: "light",
  },
  {
    id: "earthy-clay",
    name: "Earthy Clay",
    primary: "#A0522D",
    secondary: "#8B6F47",
    accent: "#C97B57",
    background: "#FDF8F3",
    foreground: "#3E2723",
    muted: "#F5E6D3",
    border: "#E0CDAB",
    mode: "light",
  },
  {
    id: "midnight",
    name: "Midnight",
    primary: "#7C3AED",
    secondary: "#A78BFA",
    accent: "#22D3EE",
    background: "#020617",
    foreground: "#E2E8F0",
    muted: "#0F172A",
    border: "#1E293B",
    mode: "dark",
  },
  {
    id: "matcha",
    name: "Matcha",
    primary: "#4D7C0F",
    secondary: "#84CC16",
    accent: "#F59E0B",
    background: "#F7F9F4",
    foreground: "#1A2E05",
    muted: "#ECF4DC",
    border: "#D9E8C0",
    mode: "light",
  },
];
